/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetailRealtimeRouteImport } from './routes/retail-realtime'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as EventsWorkshopsRouteImport } from './routes/events-workshops'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScholarshipsIndexRouteImport } from './routes/scholarships/index'
import { Route as MentorsIndexRouteImport } from './routes/mentors.index'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships/$slug'
import { Route as MentorsApplyRouteImport } from './routes/mentors/apply'
import { Route as ApiRetailRealtimeSeatsRouteImport } from './routes/api/retail-realtime/seats'
import { Route as ApiRetailRealtimeCreateOrderRouteImport } from './routes/api/retail-realtime/create-order'
import { Route as ApiRetailRealtimeBookRouteImport } from './routes/api/retail-realtime/book'

const RetailRealtimeRoute = RetailRealtimeRouteImport.update({
  id: '/retail-realtime',
  path: '/retail-realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsWorkshopsRoute = EventsWorkshopsRouteImport.update({
  id: '/events-workshops',
  path: '/events-workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIndexRoute = ScholarshipsIndexRouteImport.update({
  id: '/scholarships/',
  path: '/scholarships/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/mentors/',
  path: '/mentors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/scholarships/$slug',
  path: '/scholarships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsApplyRoute = MentorsApplyRouteImport.update({
  id: '/mentors/apply',
  path: '/mentors/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRetailRealtimeSeatsRoute = ApiRetailRealtimeSeatsRouteImport.update({
  id: '/api/retail-realtime/seats',
  path: '/api/retail-realtime/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRetailRealtimeCreateOrderRoute =
  ApiRetailRealtimeCreateOrderRouteImport.update({
    id: '/api/retail-realtime/create-order',
    path: '/api/retail-realtime/create-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRetailRealtimeBookRoute = ApiRetailRealtimeBookRouteImport.update({
  id: '/api/retail-realtime/book',
  path: '/api/retail-realtime/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/community': typeof CommunityRoute
  '/events-workshops': typeof EventsWorkshopsRoute
  '/programs': typeof ProgramsRoute
  '/retail-realtime': typeof RetailRealtimeRoute
  '/mentors/apply': typeof MentorsApplyRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/mentors/': typeof MentorsIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/api/retail-realtime/book': typeof ApiRetailRealtimeBookRoute
  '/api/retail-realtime/create-order': typeof ApiRetailRealtimeCreateOrderRoute
  '/api/retail-realtime/seats': typeof ApiRetailRealtimeSeatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/community': typeof CommunityRoute
  '/events-workshops': typeof EventsWorkshopsRoute
  '/programs': typeof ProgramsRoute
  '/retail-realtime': typeof RetailRealtimeRoute
  '/mentors/apply': typeof MentorsApplyRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/mentors': typeof MentorsIndexRoute
  '/scholarships': typeof ScholarshipsIndexRoute
  '/api/retail-realtime/book': typeof ApiRetailRealtimeBookRoute
  '/api/retail-realtime/create-order': typeof ApiRetailRealtimeCreateOrderRoute
  '/api/retail-realtime/seats': typeof ApiRetailRealtimeSeatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/community': typeof CommunityRoute
  '/events-workshops': typeof EventsWorkshopsRoute
  '/programs': typeof ProgramsRoute
  '/retail-realtime': typeof RetailRealtimeRoute
  '/mentors/apply': typeof MentorsApplyRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/mentors/': typeof MentorsIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/api/retail-realtime/book': typeof ApiRetailRealtimeBookRoute
  '/api/retail-realtime/create-order': typeof ApiRetailRealtimeCreateOrderRoute
  '/api/retail-realtime/seats': typeof ApiRetailRealtimeSeatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/community'
    | '/events-workshops'
    | '/programs'
    | '/retail-realtime'
    | '/mentors/apply'
    | '/scholarships/$slug'
    | '/mentors/'
    | '/scholarships/'
    | '/api/retail-realtime/book'
    | '/api/retail-realtime/create-order'
    | '/api/retail-realtime/seats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/community'
    | '/events-workshops'
    | '/programs'
    | '/retail-realtime'
    | '/mentors/apply'
    | '/scholarships/$slug'
    | '/mentors'
    | '/scholarships'
    | '/api/retail-realtime/book'
    | '/api/retail-realtime/create-order'
    | '/api/retail-realtime/seats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/community'
    | '/events-workshops'
    | '/programs'
    | '/retail-realtime'
    | '/mentors/apply'
    | '/scholarships/$slug'
    | '/mentors/'
    | '/scholarships/'
    | '/api/retail-realtime/book'
    | '/api/retail-realtime/create-order'
    | '/api/retail-realtime/seats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  CommunityRoute: typeof CommunityRoute
  EventsWorkshopsRoute: typeof EventsWorkshopsRoute
  ProgramsRoute: typeof ProgramsRoute
  RetailRealtimeRoute: typeof RetailRealtimeRoute
  MentorsApplyRoute: typeof MentorsApplyRoute
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
  ScholarshipsIndexRoute: typeof ScholarshipsIndexRoute
  ApiRetailRealtimeBookRoute: typeof ApiRetailRealtimeBookRoute
  ApiRetailRealtimeCreateOrderRoute: typeof ApiRetailRealtimeCreateOrderRoute
  ApiRetailRealtimeSeatsRoute: typeof ApiRetailRealtimeSeatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retail-realtime': {
      id: '/retail-realtime'
      path: '/retail-realtime'
      fullPath: '/retail-realtime'
      preLoaderRoute: typeof RetailRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-workshops': {
      id: '/events-workshops'
      path: '/events-workshops'
      fullPath: '/events-workshops'
      preLoaderRoute: typeof EventsWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/': {
      id: '/scholarships/'
      path: '/scholarships'
      fullPath: '/scholarships/'
      preLoaderRoute: typeof ScholarshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/mentors'
      fullPath: '/mentors/'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/scholarships/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/apply': {
      id: '/mentors/apply'
      path: '/mentors/apply'
      fullPath: '/mentors/apply'
      preLoaderRoute: typeof MentorsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/retail-realtime/seats': {
      id: '/api/retail-realtime/seats'
      path: '/api/retail-realtime/seats'
      fullPath: '/api/retail-realtime/seats'
      preLoaderRoute: typeof ApiRetailRealtimeSeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/retail-realtime/create-order': {
      id: '/api/retail-realtime/create-order'
      path: '/api/retail-realtime/create-order'
      fullPath: '/api/retail-realtime/create-order'
      preLoaderRoute: typeof ApiRetailRealtimeCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/retail-realtime/book': {
      id: '/api/retail-realtime/book'
      path: '/api/retail-realtime/book'
      fullPath: '/api/retail-realtime/book'
      preLoaderRoute: typeof ApiRetailRealtimeBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  CommunityRoute: CommunityRoute,
  EventsWorkshopsRoute: EventsWorkshopsRoute,
  ProgramsRoute: ProgramsRoute,
  RetailRealtimeRoute: RetailRealtimeRoute,
  MentorsApplyRoute: MentorsApplyRoute,
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
  MentorsIndexRoute: MentorsIndexRoute,
  ScholarshipsIndexRoute: ScholarshipsIndexRoute,
  ApiRetailRealtimeBookRoute: ApiRetailRealtimeBookRoute,
  ApiRetailRealtimeCreateOrderRoute: ApiRetailRealtimeCreateOrderRoute,
  ApiRetailRealtimeSeatsRoute: ApiRetailRealtimeSeatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
